services:

  postgres:	
    image: postgres:16
    container_name: TechcoreMicroservices-PostgresContainer
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - BooksKeeper-Db-Data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 554034
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default-net

  redis:
    image: redis:7-alpine
    container_name: TechcoreMicroservices-RedisContainer
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default-net
  
  mongodb:
    image: mongo:7.0
    container_name: TechcoreMicroservices-MongoContainer
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ProductReviewsDB
    volumes:
      - mongo-data:/data/db
    networks:
      - default-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: TechcoreMicroservices-RabbitMqContainer
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
    networks:
      - default-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: TechcoreMicroservices-ZookeeperContainer
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - default-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: TechcoreMicroservices-KafkaContainer
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - default-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
    - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - default-net

  analytics-worker:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.AnalyticsWorkerService/AnalyticService/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: "kafka:9093"
      KAFKA_TOPIC: "book_views"
      KAFKA_GROUP: "analytics-service-group"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - default-net

  api-gateway:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.ApiGateway/TechcoreMicroservices.ApiGateway.YarpGw/Dockerfile
    ports:
      - "5000:8081"
    environment:
      ASPNETCORE_URLS: "http://+:8081"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - default-net

  book-order-service:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.BookOrderService/TechcoreMicroservices.BookOrderService.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_URLS: "http://+:8081"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5001:8081
    networks:
      - default-net

  book-review-service:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.BookReviewService/TechcoreMicroservices.BookReviewService.API/Dockerfile
    depends_on:
      - mongodb
      - redis
      - postgres
      - rabbitmq
    ports:
      - 5002:8081
    environment:
      ASPNETCORE_URLS: "http://+:8081"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - default-net

  book-service-books:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.BookService/TechcoreMicroservices.BookService.Books.API/Dockerfile
    depends_on:
      - mongodb
      - redis
      - postgres
      - rabbitmq
    ports:
      - 5003:8081
    environment:
      ASPNETCORE_URLS: "http://+:8081"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - default-net

  book-service-authors:
    build:
      context: .
      dockerfile: ./src/TechcoreMicroservices.BookService/TechcoreMicroservices.BookService.Authors.API/Dockerfile
    depends_on:
      - mongodb
      - redis
      - postgres
      - rabbitmq
    ports:
      - 5004:8081
    environment:
      ASPNETCORE_URLS: "http://+:8081"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - default-net

  zipkin:
    image: openzipkin/zipkin
    container_name: TechcoreMicroservices-ZipkinContainer
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem
    networks:
      - default-net

volumes:
  BooksKeeper-Db-Data:
  redis-data:
  mongo-data:
  rabbitmq-data: 
  
networks:
  default-net:
    driver: bridge