global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8081"]
  
  - job_name: "book-review-service"
    static_configs:
      - targets: ["book-review-service:8081"]
    
  - job_name: "book-service-books"
    static_configs:
      - targets: ["book-service-books:8081"]
  
  - job_name: "book-service-authors"
    static_configs:
      - targets: ["book-service-authors:8081"]
  
  - job_name: "book-order-service"
    static_configs:
      - targets: ["book-order-service:8081"]