apiVersion: v1
kind: ConfigMap
metadata:
  name: author-service-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "DefaultConnection": "Host=10.97.38.90;Port=5432;Database=postgres;Username=postgres;Password=PLACEHOLDER_DB_PASSWORD"
      },
      "ApiSettings": {
        "Version": "v1.0",
        "Author": "Kirill Zhestkov",
        "Type": "REST-API (CRUD)",
        "Company": "Techcore"
      },
      "Redis": {
        "RedisConnectionString": "redis-master.default.svc.cluster.local:6379,password=PLACEHOLDER_REDIS_PASSWORD",
        "InstanceName": "AuthorsAPI:"
      },
      "RabbitMqSettings": {
        "Username": "admin",
        "Password": "PLACEHOLDER_RABBIT_PASSWORD"
      },
      "KafkaSettings": {
        "Book": {
          "BootstrapServers": "kafka:9093",
          "Topic": "book-views"
        }
      },
      "OTelSettings": {
        "ServiceName": "book-service-authors"
      }
    }
