apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-order-service-deployment
  labels:
    app: book-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-order-service
  template:
    metadata:
      labels:
        app: book-order-service
    spec:
      containers:
        - name: book-order-service
          image: techcoremicroservicesbookorderserviceapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          envFrom:
            - secretRef:
                name: bookorder-service-secrets
      volumes:
        - name: config-volume
          configMap:
            name: bookorder-service-config
            items:
              - key: appsettings.json
                path: appsettings.json
---
apiVersion: v1
kind: Service
metadata:
  name: book-order-service
spec:
  type: NodePort
  selector:
    app: book-order-service
  ports:
    - port: 8083
      targetPort: 8080
      nodePort: 30083