apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service-deployment
  labels:
    app: author-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: techcoremicroservicesbookserviceauthorsapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config   
              readOnly: true
          envFrom:
            - secretRef:
                name: author-service-secrets
      volumes:
        - name: config-volume
          configMap:
            name: author-service-config
            items:
              - key: appsettings.json
                path: appsettings.json 
---
apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  type: NodePort
  selector:
    app: author-service
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30081
