apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: techcoremicroservices-book-service-books
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.k8s.json
      volumes:
        - name: config-volume
          configMap:
            name: book-service-config