apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review-service-deployment
  labels:
    app: book-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review-service
  template:
    metadata:
      labels:
        app: book-review-service
    spec:
      containers:
        - name: book-review-service
          image: techcoremicroservicesbookreviewserviceapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: book-review-service
spec:
  type: NodePort
  selector:
    app: book-review-service
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30082